language: php
php:
  - 7.1.9
install:
  - travis_retry composer install --no-interaction --no-suggest
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
before_deploy:
  - zip rockschtar_metarevisions_${TRAVIS_TAG}.zip ${TRAVIS_BUILD_DIR}
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: rockschtar_metarevisions_${TRAVIS_TAG}
  skip_cleanup: true
  on:
    tags: true