language: php
php:
  - 7.1.9
install:
  - travis_retry composer install --no-interaction --no-suggest
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  skip_cleanup: true
  on:
    tags: true