language: php
php:
  - 7.1.9
install:
  - travis_retry composer install --no-interaction --no-suggest
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
before_deploy:
  - zip ${TRAVIS_BUILD_DIR}/artifact.zip ${TRAVIS_BUILD_DIR}
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: ${TRAVIS_BUILD_DIR}/artifact.zip
  skip_cleanup: true
